# Generated by Django 3.2.13 on 2022-11-22 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('overview', models.TextField()),
                ('overview_en', models.TextField()),
                ('poster_path', models.CharField(max_length=200)),
                ('vote_count', models.IntegerField()),
                ('vote_average', models.FloatField()),
                ('backdrop_path', models.CharField(max_length=200)),
                ('genres', models.ManyToManyField(to='movies.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Similar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similar1_idx', models.IntegerField()),
                ('similar1_title', models.CharField(max_length=100)),
                ('similar1_poster_path', models.CharField(max_length=200)),
                ('similar2_idx', models.IntegerField()),
                ('similar2_title', models.CharField(max_length=100)),
                ('similar2_poster_path', models.CharField(max_length=200)),
                ('similar3_idx', models.IntegerField()),
                ('similar3_title', models.CharField(max_length=100)),
                ('similar3_poster_path', models.CharField(max_length=200)),
                ('similar4_idx', models.IntegerField()),
                ('similar4_title', models.CharField(max_length=100)),
                ('similar4_poster_path', models.CharField(max_length=200)),
                ('similar5_idx', models.IntegerField()),
                ('similar5_title', models.CharField(max_length=100)),
                ('similar5_poster_path', models.CharField(max_length=200)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
